# Generated by Django 2.2.7 on 2020-03-28 04:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('license_plate', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='车牌号')),
                ('brand', models.CharField(blank=True, max_length=20, null=True, verbose_name='品牌')),
                ('color', models.CharField(max_length=5, null=True, verbose_name='颜色')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '车辆',
                'verbose_name_plural': '车辆',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='', max_length=200, verbose_name='资源路径')),
                ('desc', models.CharField(default='', max_length=200, verbose_name='描述信息')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=None, to='cars.Car', verbose_name='车辆')),
                ('user', models.ForeignKey(on_delete=None, to='users.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '图片',
            },
        ),
    ]
