# Generated by Django 2.2.7 on 2020-04-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=10, null=True, verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('black', '黑色'), ('white', '白色'), ('red', '红色'), ('blue', '蓝色'), ('green', '绿色'), ('gray', '灰色'), ('yellow', '黄色'), ('brown', '棕色')], max_length=10, null=True, verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='car',
            name='confidence',
            field=models.IntegerField(null=True, verbose_name='置信度'),
        ),
        migrations.AlterField(
            model_name='car',
            name='p1',
            field=models.IntegerField(null=True, verbose_name='坐标1'),
        ),
        migrations.AlterField(
            model_name='car',
            name='p2',
            field=models.IntegerField(null=True, verbose_name='坐标2'),
        ),
        migrations.AlterField(
            model_name='car',
            name='p3',
            field=models.IntegerField(null=True, verbose_name='坐标3'),
        ),
        migrations.AlterField(
            model_name='car',
            name='p4',
            field=models.IntegerField(null=True, verbose_name='坐标4'),
        ),
    ]
