# Generated by Django 2.2.7 on 2020-04-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20200405_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='p1',
            field=models.IntegerField(null=True, verbose_name='p1'),
        ),
        migrations.AlterField(
            model_name='car',
            name='p2',
            field=models.IntegerField(null=True, verbose_name='p2'),
        ),
        migrations.AlterField(
            model_name='car',
            name='p3',
            field=models.IntegerField(null=True, verbose_name='p3'),
        ),
        migrations.AlterField(
            model_name='car',
            name='p4',
            field=models.IntegerField(null=True, verbose_name='p4'),
        ),
    ]
