# Generated by Django 2.2.7 on 2020-04-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVeriRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='验证码')),
                ('email', models.EmailField(max_length=50, verbose_name='用户邮箱')),
                ('send_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='发送时间')),
                ('exprie_time', models.DateTimeField(null=True)),
                ('email_type', models.CharField(choices=[('register', '注册邮件'), ('forget', '找回密码')], max_length=10)),
            ],
            options={
                'verbose_name': '邮件验证码',
                'verbose_name_plural': '邮件验证码',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('email', models.EmailField(default='', max_length=50, verbose_name='用户邮箱')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
    ]
