# Generated by Django 2.2.7 on 2020-04-13 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_userprofile_create_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='nick_name',
            new_name='user_name',
        ),
    ]
