# Generated by Django 2.2.7 on 2020-04-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_userprofile_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverirecord',
            name='exprie_time',
        ),
        migrations.AddField(
            model_name='emailverirecord',
            name='expire_time',
            field=models.DateTimeField(null=True, verbose_name='过期时间'),
        ),
    ]
