# Generated by Django 2.2.7 on 2020-04-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercar',
            name='plate',
            field=models.CharField(max_length=10, verbose_name='查询值'),
        ),
    ]
